//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Classroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classroom()
        {
            this.Course = new HashSet<Course>();
        }

        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string ClassroomName { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string ClassroomDescription { get; set; }
        [Required]
        [Range(-90.0000000000000, 90.0000000000000000, ErrorMessage = "Latitude must between -90 to 90")]
        public string ClassroomLatitude { get; set; }
        [Required]
        [Range(-180.0000000000000, 180.0000000000000, ErrorMessage = "Longitude must between -180 to 180")]
        public string ClassroomLongitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
    }
}
