//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Booking = new HashSet<Booking>();
            this.Rating = new HashSet<Rating>();
        }

        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string CourseName { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string CourseDescription { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime CourseTime { get; set; }
        [Range(1, 10, ErrorMessage = "Rating must between 1 to 10, only integer accepted")]
        public string CourseRating { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string TrainerName { get; set; }
        [Required]
        public int ClassroomId { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> CourseEndTime { get; set; }

        public virtual Classroom Classroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
