//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [Range(1, 10, ErrorMessage = "Rating must between 1 to 10, only integer accepted")]
        public string RatingValue { get; set; }
        public string UserId { get; set; }
        [Required]
        public int CourseId { get; set; }
        public string UserName { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
